version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "src/Auth0.AspNetCore.Authentication.Api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
    labels:
      - "deps:nuget"

  - package-ecosystem: "nuget"
    directory: "tests/Auth0.AspNetCore.Authentication.Api.UnitTests"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
    labels:
      - "deps:nuget"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
    labels:
      - "deps:github-actions"
